version: "3"

tasks:
  default:
    cmds:
      - task --list

  run:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Runs the script to cross-post
    cmds:
      - source .venv/bin/activate && python -m src

  check:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Lint and run tests
    cmds:
      - task: lint
      - task: test

  lint:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Lint the code using ruff
    cmds:
      - ruff check --fix

  test:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Runs the tests
    cmds:
      - pytest

  testv:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Runs the tests with verbose output
    cmds:
      - pytest -vv

  install:
    desc: "{{ .DESC }}"
    summary: "{{ .DESC }}"
    vars:
      DESC: Install the dependencies in a virtual environment, using the tool uv.
    cmds:
      - uv venv
      - source venv/bin/activate && uv pip install -r requirements.txt
